'use strict'; const { URL } = require('url'); function setSecurityHeaders(res) { res.setHeader('X-Content-Type-Options', 'nosniff'); res.setHeader('X-Frame-Options', 'DENY'); res.setHeader('Referrer-Policy', 'strict-origin-when-cross-origin'); res.setHeader('Permissions-Policy', 'camera=(), microphone=(), geolocation=()');
} function applyCors(req, res, corsOrigin) { const origin = req.headers.origin || ''; const allowedOrigin = 'https://neuralgpt.store'; if (origin === allowedOrigin) { res.setHeader('Access-Control-Allow-Origin', allowedOrigin); res.setHeader('Vary', 'Origin'); } res.setHeader('Access-Control-Allow-Methods', 'GET,POST,OPTIONS'); res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Stripe-Signature');
} function sendJson(res, statusCode, payload) { setSecurityHeaders(res); res.statusCode = statusCode; res.setHeader('Content-Type', 'application/json; charset=utf-8'); res.end(JSON.stringify(payload));
} function sendError(res, statusCode, error, detail) { const body = { ok: false, error: String(error || 'unknown_error') }; if (detail) body.detail = String(detail); return sendJson(res, statusCode, body);
} function parseUrl(req) { return new URL(req.url, 'http://runtime.local');
} function readRawBody(req, maxBytes) { return new Promise((resolve, reject) => { const chunks = []; let size = 0; req.on('data', (chunk) => { size += chunk.length; if (size > maxBytes) { reject(new Error('payload_too_large')); req.destroy(); return; } chunks.push(chunk); }); req.on('end', () => resolve(Buffer.concat(chunks))); req.on('error', reject); });
} async function readJsonBody(req, maxBytes) { const raw = await readRawBody(req, maxBytes); if (!raw.length) return {}; try { return JSON.parse(raw.toString('utf8')); } catch (_error) { throw new Error('invalid_json_body'); }
} async function readMultipartBody(req, maxBytes) { const contentType = String(req.headers['content-type'] || ''); const match = contentType.match(/boundary=([^;]+)/i); if (!match || !match[1]) throw new Error('multipart_boundary_missing'); const boundary = match[1].trim().replace(/^"|"$/g, ''); const raw = await readRawBody(req, maxBytes); const delimiter = Buffer.from('--' + boundary); const closeDelimiter = Buffer.from('--' + boundary + '--'); const fields = {}; const files = []; let cursor = 0; while (cursor < raw.length) { let partStart = raw.indexOf(delimiter, cursor); if (partStart < 0) break; if (raw.indexOf(closeDelimiter, partStart) === partStart) break; partStart += delimiter.length; if (raw[partStart] === 13 && raw[partStart + 1] === 10) partStart += 2; const nextBoundary = raw.indexOf(delimiter, partStart); if (nextBoundary < 0) break; let part = raw.slice(partStart, nextBoundary); if (part.length >= 2 && part[part.length - 2] === 13 && part[part.length - 1] === 10) { part = part.slice(0, part.length - 2); } const headerEnd = part.indexOf(Buffer.from('\r\n\r\n')); if (headerEnd < 0) { cursor = nextBoundary; continue; } const headerText = part.slice(0, headerEnd).toString('utf8'); const data = part.slice(headerEnd + 4); const disposition = headerText.split('\r\n').find((line) => /^content-disposition:/i.test(line)) || ''; const nameMatch = disposition.match(/name="([^"]+)"/i); if (!nameMatch) { cursor = nextBoundary; continue; } const name = nameMatch[1]; const fileNameMatch = disposition.match(/filename="([^"]*)"/i); if (fileNameMatch && fileNameMatch[1]) { files.push({ fieldName: name, filename: fileNameMatch[1], size: data.length }); } else { fields[name] = data.toString('utf8'); } cursor = nextBoundary; } return { fields, files };
} module.exports = { applyCors, parseUrl, readJsonBody, readMultipartBody, readRawBody, sendError, sendJson
};
